# Generated by Django 5.2.5 on 2026-02-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("admin", "Admin"), ("owner", "Owner"), ("driver", "Driver")],
                max_length=10,
                null=True,
            ),
        ),
    ]
