# Generated by Django 5.2.5 on 2026-03-07 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_bus"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="driver",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_bus",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
