# Generated by Django 5.2.5 on 2026-03-26 07:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="verification_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
