# Generated by Django 5.2.5 on 2026-03-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_customuser_verification_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
