# Generated by Django 5.2.5 on 2026-03-10 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_bus_driver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="driver",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_bus",
                to="accounts.driverprofile",
            ),
        ),
    ]
