# Generated by Django 5.2.5 on 2026-03-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_bus_driver"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="bus_images/"),
        ),
    ]
